export * from "./2fa.ts";
export * from "./auth.ts";
export * from "./base_client.ts";
export * from "./bots.ts";
export * from "./buttons.ts";
export * from "./chats.ts";
export * from "./dialogs.ts";
export * from "./downloads.ts";
export * from "./message_parse.ts";
export * from "./messages.ts";
export * from "./telegram_client.ts";
export * from "./updates.ts";
export * from "./uploads.ts";
export * from "./users.ts";

// aliases for compat with node-gramjs
export * as twoFa from "./2fa.ts";
export * as auth from "./auth.ts";
export * as telegramBaseClient from "./base_client.ts";
export * as bots from "./bots.ts";
export * as buttons from "./buttons.ts";
export * as chats from "./chats.ts";
export * as dialogs from "./dialogs.ts";
export * as downloads from "./downloads.ts";
export * as messageParse from "./message_parse.ts";
export * as message from "./messages.ts";
export * as tgClient from "./abstract_telegram_client.ts";
export * as updates from "./updates.ts";
export * as uploads from "./uploads.ts";
export * as users from "./users.ts";
